global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'httpd'
    static_configs:
      - targets: [ 'httpd:80' ]
    params:
      modules: [""]  # adds ?modules in the requested URL

  - job_name: 'httpd-cache'
    static_configs:
      - targets: [ 'httpd:80' ]
    metrics_path: /cache-metrics