{
 "title": "mod_prom_status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "HTTPd version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(1, httpd_info)", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "httpd_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MPM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(1, httpd_info)", "legendFormat": "{{mpm}}" }
   ]
  },
  {
   "title": "Max servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (httpd_scoreboard))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads per child",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(httpd_scoreboard) / count(count by (server) (httpd_scoreboard))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global scoreboard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(httpd_scoreboard) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Started servers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (httpd_scoreboard{state=\"open_slot\"} == 0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count by (server) (httpd_scoreboard))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busy threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(httpd_scoreboard{state!~\"idle|open_slot\"})",
     "legendFormat": "__auto"
    },
    { "expr": "sum(httpd_scoreboard)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(httpd_accesses_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "round(increase(httpd_sent_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded modules",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "httpd_module    ", "legendFormat": "__auto" }
   ]
  }
 ]
}